Received: from t34 [127.0.0.1] by mydomain.ru [127.0.0.1] with ESMTP; Sat 16 Jan 2010 03:59:34 +0300
Date: Sat, 16 Jan 2010 03:59:34 +0300
Subject: 22222
From: "4444444444" <333333333@rrrrrrr.ru>
To: test@localhost
Subject: 22222
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="a*****-*****-*****"



--a*****-*****-*****
Content-type: text/html; charset="windows-1251"
Content-Transfer-Encoding: quoted-printable

ФИО 4444444444
E-mail: 333333333@rrrrrrr.ru
Тема: 22222
Текст письма: 55555555

--a*****-*****-*****
Content-Type: application/octet-stream;name=""
Content-Transfer-Encoding:base64
Content-Disposition:attachment


a*****-*****-*****--


